version: '2'
services:
  mongodb:
    image: mongo:latest
    ports:
    - 27018:27017
    volumes:
    - data:/data/db
    - data:/data/configdb
    restart: always
    hostname: mongodb
    container_name: mongodb
    command: --smallfiles

  widget:
    image: garystafford/widget-service-standalone:latest
    ports:
    - 8030:8030
    depends_on:
    - mongodb
    hostname: widget
    container_name: widget
    environment:
    - SPRING_PROFILES_ACTIVE=production

  elk:
    image: sebp/elk:latest
    ports:
    - 5601:5601
    - 9200:9200
    - 5044:5044
    - 5000:5000
    hostname: elk
    container_name: elk

volumes:
  data: {}
