spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: widgets

logging:
  file: widget-service.log
  level:
    root: DEBUG

server:
  port: 8030

---

spring:
  profiles: testing
  data:
    mongodb:
      host: mongodb

logging:
  level:
    root: DEBUG